### ISSUE TITLE
Service Discovery iApp isn't working in Azure US Gov environment

### ISSUE THREAD

**Issue by garyluf5** [F5Networks/f5-cloud-iapps#9] opened 2018-12-03 21:19 UTC
We have customers wanted to use Service Discovery iApp in Azure Gov Cloud. However, the current version isn't working

**Comment by wduongf5** [comment] 2019-05-13 21:12
Closing. Duplicate of issue 15 which we've already created an internal issue to track.

**Closed by wduongf5** 2019-05-13 21:12 UTC
